### ISSUE TITLE
Is 2.11 supported?

### ISSUE THREAD

**Issue by ittaiz** [retronym/classpath-shrinker#1]
Hi,
I'm looking into using this in a codebase using 2.11.
Is this supported?

**Comment by ittaiz** [comment]
ping?

**Comment by SethTisue** [comment]
perhaps @retronym would take a pull request that adds 2.11 support. I doubt it has been tried — perhaps you'd find that there was no difficulty at all! or if you hit some difficulty, you could report your findings and we'd learn something.

**Comment by retronym** [comment]
Scala Center now maintains this plugin over in https://github.com/scalacenter/classpath-shrinker. Could you pose the question in that tracker?

I haven't tested this plugin with 2.11, but there is a good chance it will, or only require small changes to be compatible.

I'll update the description of this repo and disable the issue tracker to avoid future confusion.
